export type Employee = {
  keyV: string;
  lastName: string;
  email: string;
  jobTitle: string;
  salary: number;
  startDate: string;
};

export const data: Employee[] = [
  {
    keyV: 'Joseph',
    lastName: 'Hand',
    email: 'Alabama',
    salary: 57752,
    jobTitle: 'Y',
    startDate: '2022-12-28T20:59:36.586Z',
  },
  {
    keyV: 'Paula',
    lastName: 'Kohler',
    email: 'Alaska',
    salary: 47029,
    jobTitle: 'Y',
    startDate: '2023-01-04T08:03:36.832Z',
  },
  {
    keyV: 'Domenic',
    lastName: 'Cassin',
    email: 'Alaska',
    salary: 55602,
    jobTitle: 'Y',
    startDate: '2022-02-07T13:34:22.224Z',
  },
  {
    keyV: 'Rey',
    lastName: 'Runte',
    email: 'Alabama',
    salary: 88782,
    jobTitle: 'N',
    startDate: '2022-10-02T00:14:02.192Z',
  },
  {
    keyV: 'Buck',
    lastName: 'Mosciski',
    email: 'Alabama',
    salary: 95101,
    jobTitle: 'Y',
    startDate: '2022-11-14T10:56:33.026Z',
  },
  {
    keyV: 'Johnson',
    lastName: 'Nitzsche',
    email: 'Alabama',
    salary: 96104,
    jobTitle: 'N',
    startDate: '2022-08-12T22:15:41.531Z',
  },
  {
    keyV: 'Silas',
    lastName: 'Hermiston',
    email: 'Alabama',
    salary: 64532,
    jobTitle: 'Y',
    startDate: '2022-06-03T16:42:52.698Z',
  },
  {
    keyV: 'Kailey',
    lastName: 'Bergstrom',
    email: 'Alabama',
    salary: 26096,
    jobTitle: 'Y',
    startDate: '2022-10-17T21:12:54.687Z',
  },
  {
    keyV: 'Lilian',
    lastName: 'Tromp',
    email: 'Alabama',
    salary: 72692,
    jobTitle: 'Y',
    startDate: '2022-09-13T11:55:16.045Z',
  },
  {
    keyV: 'Maxine',
    lastName: 'Schmidt',
    email: 'Alabama',
    salary: 89317,
    jobTitle: 'Y',
    startDate: '2022-07-01T07:29:03.182Z',
  },
  {
    keyV: 'Robyn',
    lastName: 'Stroman',
    email: 'Alabama',
    salary: 9167,
    jobTitle: 'Y',
    startDate: '2022-09-04T16:39:46.068Z',
  },
  {
    keyV: 'Asha',
    lastName: 'Rolfson',
    email: 'Alabama',
    salary: 45363,
    jobTitle: 'Y',
    startDate: '2022-11-14T16:19:21.814Z',
  },
  {
    keyV: 'Serena',
    lastName: 'Reynolds',
    email: 'Alabama',
    salary: 11166,
    jobTitle: 'Y',
    startDate: '2022-08-03T03:54:24.200Z',
  },
  {
    keyV: 'Ulices',
    lastName: 'Buckridge',
    email: 'Alabama',
    salary: 97400,
    jobTitle: 'Y',
    startDate: '2022-02-20T10:26:24.947Z',
  },
  {
    keyV: 'Paxton',
    lastName: 'Gottlieb',
    email: 'Alabama',
    salary: 84030,
    jobTitle: 'Y',
    startDate: '2022-07-07T10:34:23.518Z',
  },
  {
    keyV: 'Monserrat',
    lastName: 'Walter',
    email: 'Alabama',
    salary: 16797,
    jobTitle: 'Y',
    startDate: '2022-05-16T20:27:12.189Z',
  },
  {
    keyV: 'Alva',
    lastName: 'Hodkiewicz',
    email: 'Washington',
    salary: 48676,
    jobTitle: 'N',
    startDate: '2022-12-20T16:49:15.685Z',
  },
  {
    keyV: 'Marc',
    lastName: 'Willms',
    email: 'Alabama',
    salary: 21843,
    jobTitle: 'N',
    startDate: '2023-01-09T09:13:15.011Z',
  },
  {
    keyV: 'Alexys',
    lastName: 'Hills',
    email: 'Washington',
    salary: 67328,
    jobTitle: 'N',
    startDate: '2022-10-25T14:07:34.391Z',
  },
  {
    keyV: 'Annamae',
    lastName: 'Braun',
    email: 'Alabama',
    salary: 76900,
    jobTitle: 'N',
    startDate: '2022-07-28T19:35:28.462Z',
  },
  {
    keyV: 'Cletus',
    lastName: 'Gleason',
    email: 'Alabama',
    salary: 38627,
    jobTitle: 'N',
    startDate: '2022-06-20T10:51:23.449Z',
  },
];

export const usStates = [
  { value: "Alabama", label: "Alabama_label" },
  { value: "Alaska", label: "Alaska_label" },
  { value: "Arizona", label: "Arizona_label" },
  { value: "Arkansas", label: "Arkansas_label" },
  { value: "California", label: "California_label" },
  { value: "Colorado", label: "Colorado_label" },
  { value: "Connecticut", label: "Connecticut_label" },
  { value: "Delaware", label: "Delaware_label" },
  { value: "Florida", label: "Florida_label" },
  { value: "Georgia", label: "Georgia_label" },
  { value: "Hawaii", label: "Hawaii_label" },
  { value: "Idaho", label: "Idaho_label" },
  { value: "Illinois", label: "Illinois_label" },
  { value: "Indiana", label: "Indiana_label" },
  { value: "Iowa", label: "Iowa_label" },
  { value: "Kansas", label: "Kansas_label" },
  { value: "Kentucky", label: "Kentucky_label" },
  { value: "Louisiana", label: "Louisiana_label" },
  { value: "Maine", label: "Maine_label" },
  { value: "Maryland", label: "Maryland_label" },
  { value: "Massachusetts", label: "Massachusetts_label" },
  { value: "Michigan", label: "Michigan_label" },
  { value: "Minnesota", label: "Minnesota_label" },
  { value: "Mississippi", label: "Mississippi_label" },
  { value: "Missouri", label: "Missouri_label" },
  { value: "Montana", label: "Montana_label" },
  { value: "Nebraska", label: "Nebraska_label" },
  { value: "Nevada", label: "Nevada_label" },
  { value: "New Hampshire", label: "New Hampshire_label" },
  { value: "New Jersey", label: "New Jersey_label" },
  { value: "New Mexico", label: "New Mexico_label" },
  { value: "New York", label: "New York_label" },
  { value: "North Carolina", label: "North Carolina_label" },
  { value: "North Dakota", label: "North Dakota_label" },
  { value: "Ohio", label: "Ohio_label" },
  { value: "Oklahoma", label: "Oklahoma_label" },
  { value: "Oregon", label: "Oregon_label" },
  { value: "Pennsylvania", label: "Pennsylvania_label" },
  { value: "Rhode Island", label: "Rhode Island_label" },
  { value: "South Carolina", label: "South Carolina_label" },
  { value: "South Dakota", label: "South Dakota_label" },
  { value: "Tennessee", label: "Tennessee_label" },
  { value: "Texas", label: "Texas_label" },
  { value: "Utah", label: "Utah_label" },
  { value: "Vermont", label: "Vermont_label" },
  { value: "Virginia", label: "Virginia_label" },
  { value: "Washington", label: "Washington_label" },
  { value: "West Virginia", label: "West Virginia_label" },
  { value: "Wisconsin", label: "Wisconsin_label" },
  { value: "Wyoming", label: "Wyoming_label" },
  { value: "Puerto Rico", label: "Puerto Rico_label" },
];
