export type User = {
    id: string;
    firstName: string;
    lastName: string;
    email: string;
    lastDate: string;
    state: string;
  };
  
export const fakeData: User[] = [
    {
      id: '9s41rp',
      firstName: 'Kelvin',
      lastName: 'ho',
      email: 'Jerod14@hotmail.com',
      lastDate: '2025-02-01',
      state: 'Ohio',
    },
    {
      id: '08m6rx',
      firstName: 'Molly',
      lastName: 'kim',
      email: 'Hugh.Dach79@hotmail.com',
      lastDate: '2025-02-01',
      state: 'Rhode Island',
    },
    {
      id: '5ymtrc',
      firstName: 'Henry',
      lastName: 'carrot',
      email: 'Camden.Macejkovic@yahoo.com',
      lastDate: '2025-02-01',
      state: 'California',
    },
    {
      id: 'ek5b97',
      firstName: 'Glenda',
      lastName: 'park',
      email: 'Eric0@yahoo.com',
      lastDate: '2025-02-01',
      state: 'Montana',
    },
    {
      id: 'xxtydd',
      firstName: 'Leone',
      lastName: 'lee',
      email: 'Ericka_Mueller52@yahoo.com',
      lastDate: '2025-02-01',
      state: 'Colorado',
    },
    {
      id: 'wzxj9m',
      firstName: 'Mckenna',
      lastName: '2025-02-01',
      email: 'Veda_Feeney@yahoo.com',
      lastDate: '2025-02-01',
      state: 'New York',
    },
    {
      id: '21dwtz',
      firstName: 'Wyman',
      lastName: 'yang',
      email: 'Melvin.Pacocha@yahoo.com',
      lastDate: '2025-02-01',
      state: 'Montana',
    },
    {
      id: 'o8oe4k',
      firstName: 'Janick',
      lastName: 'shin',
      email: 'Delfina12@gmail.com',
      lastDate: '2025-02-01',
      state: 'Nebraska',
    },
  ];
  
  //50 us states array
  export const usStates = [
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming',
    'Puerto Rico',
];
