"use client";

import "@mantine/core/styles.css";
import {
    ColorSchemeScript,
    Flex,
    MantineProvider,
    mantineHtmlProps,
    rem,
} from "@mantine/core";

import { useState } from "react";
import { Text } from "@mantine/core";
import classes from "./NavbarSegmented.module.css";
import Link from "next/link";
import { AppShell } from "@mantine/core";
import { useDisclosure } from "@mantine/hooks";
import {
    QueryCache,
    QueryClient,
    QueryClientProvider,
} from "@tanstack/react-query";
import { ModalsProvider } from "@mantine/modals";
import ActionToggle from "./components/actionToggle";
import toast, { Toaster } from "react-hot-toast";
// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

const tabs = [
    { link: "/grid/modal", label: "modal" },
    { link: "/grid/inline", label: "inline" },
];

const queryClient = new QueryClient({
    defaultOptions: {
        queries: {
            // 클라이언트에서 즉시 재가져오지 않도록 기본 staleTime을 0보다 크게 설정하는 것이 일반적
            staleTime: 60_000,
        },
    },
    queryCache: new QueryCache({
        onError: (error, query) => {
            if (query.state.status === "error") {
                toast.error(`오류가 발생했습니다 ➡️ ${error.message}`);
            }
        },
    }),
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const [opened, { toggle }] = useDisclosure();
    const [active, setActive] = useState("");
    return (
        <html lang="en" {...mantineHtmlProps}>
            <head>
                <ColorSchemeScript />
            </head>
            <body>
                <QueryClientProvider client={queryClient}>
                    <MantineProvider>
                        <ModalsProvider>
                            <AppShell
                                navbar={{
                                    width: 200,
                                    breakpoint: "sm",
                                    collapsed: { mobile: !opened },
                                }}
                                header={{
                                    height: "auto",
                                }}
                                padding="md"
                            >
                                <AppShell.Header>
                                    <Flex
                                        p="10px 20px"
                                        align={"center"}
                                        justify={"flex-end"}
                                    >
                                        <ActionToggle />
                                    </Flex>
                                </AppShell.Header>

                                <AppShell.Navbar p="md">
                                    <nav className={classes.navbar}>
                                        <div>
                                            <Text
                                                fw={500}
                                                size="sm"
                                                className={classes.title}
                                                c="dimmed"
                                                mb="xs"
                                            >
                                                메뉴
                                            </Text>
                                        </div>

                                        <div className={classes.navbarMain}>
                                            {tabs.map((item) => (
                                                <Link
                                                    className={classes.link}
                                                    data-active={
                                                        item.label === active ||
                                                        undefined
                                                    }
                                                    href={item.link}
                                                    key={item.label}
                                                    onClick={(event) => {
                                                        setActive(item.label);
                                                    }}
                                                >
                                                    <span>{item.label}</span>
                                                </Link>
                                            ))}
                                        </div>
                                    </nav>
                                </AppShell.Navbar>

                                <AppShell.Main
                                    pt={`calc(${rem(60)} + var(--mantine-spacing-md))`}
                                >
                                    {children}
                                </AppShell.Main>
                            </AppShell>
                            <Toaster
                                position="top-center"
                                reverseOrder={false}
                            />
                        </ModalsProvider>
                    </MantineProvider>
                    <ReactQueryDevtools />
                </QueryClientProvider>
            </body>
        </html>
    );
}
