export const fakeData = [
    {
        id: "9s41rp",
        wdate: "2025-02-07 14:02:13",
        firstName: "Kelvin",
        lastName: "Langosh",
        email: "Y",
        state: "Ohio",
    },
    {
        id: "08m6rx",
        wdate: "2025-02-07 14:02:13",
        firstName: "Molly",
        lastName: "Purdy",
        email: "N",
        state: "Rhode Island",
    },
    {
        id: "5ymtrc",
        wdate: "2025-02-07 14:02:13",
        firstName: "Henry",
        lastName: "Lynch",
        email: "Y",
        state: "California",
    },
    {
        id: "ek5b97",
        wdate: "2025-02-07 14:02:13",
        firstName: "Glenda",
        lastName: "Douglas",
        email: "Y",
        state: "Montana",
    },
    {
        id: "xxtydd",
        wdate: "2025-02-07 14:02:13",
        firstName: "Leone",
        lastName: "Williamson",
        email: "Y",
        state: "Colorado",
    },
    {
        id: "wzxj9m",
        wdate: "2025-02-07 14:02:13",
        firstName: "Mckenna",
        lastName: "Friesen",
        email: "Y",
        state: "New York",
    },
    {
        id: "21dwtz",
        wdate: "2025-02-07 14:02:13",
        firstName: "Wyman",
        lastName: "Jast",
        email: "Y",
        state: "Montana",
    },
    {
        id: "o8oe4k",
        wdate: "2025-02-07 14:02:13",
        firstName: "Janick",
        lastName: "Willms",
        email: "Y",
        state: "Nebraska",
    },
    {
        id: "o8eoe4k",
        wdate: "2025-02-07 14:02:13",
        firstName: "Janick",
        lastName: "Willms",
        email: "Y",
        state: "Nebraska",
    },
    {
        id: "o8ogfhfge4k",
        wdate: "2025-02-07 14:02:13",
        firstName: "Janick",
        lastName: "Willms",
        email: "Y",
        state: "Nebraska",
    },
    {
        id: "dfho8oe4k",
        wdate: "2025-02-07 14:02:13",
        firstName: "Janick",
        lastName: "Willms",
        email: "Y",
        state: "Nebraska",
    },
];

//50 us states array
export const usStates = [
    { value: "Alabama", label: "Alabama_label" },
    { value: "Alaska", label: "Alaska_label" },
    { value: "Arizona", label: "Arizona_label" },
    { value: "Arkansas", label: "Arkansas_label" },
    { value: "California", label: "California_label" },
    { value: "Colorado", label: "Colorado_label" },
    { value: "Connecticut", label: "Connecticut_label" },
    { value: "Delaware", label: "Delaware_label" },
    { value: "Florida", label: "Florida_label" },
    { value: "Georgia", label: "Georgia_label" },
    { value: "Hawaii", label: "Hawaii_label" },
    { value: "Idaho", label: "Idaho_label" },
    { value: "Illinois", label: "Illinois_label" },
    { value: "Indiana", label: "Indiana_label" },
    { value: "Iowa", label: "Iowa_label" },
    { value: "Kansas", label: "Kansas_label" },
    { value: "Kentucky", label: "Kentucky_label" },
    { value: "Louisiana", label: "Louisiana_label" },
    { value: "Maine", label: "Maine_label" },
    { value: "Maryland", label: "Maryland_label" },
    { value: "Massachusetts", label: "Massachusetts_label" },
    { value: "Michigan", label: "Michigan_label" },
    { value: "Minnesota", label: "Minnesota_label" },
    { value: "Mississippi", label: "Mississippi_label" },
    { value: "Missouri", label: "Missouri_label" },
    { value: "Montana", label: "Montana_label" },
    { value: "Nebraska", label: "Nebraska_label" },
    { value: "Nevada", label: "Nevada_label" },
    { value: "New Hampshire", label: "New Hampshire_label" },
    { value: "New Jersey", label: "New Jersey_label" },
    { value: "New Mexico", label: "New Mexico_label" },
    { value: "New York", label: "New York_label" },
    { value: "North Carolina", label: "North Carolina_label" },
    { value: "North Dakota", label: "North Dakota_label" },
    { value: "Ohio", label: "Ohio_label" },
    { value: "Oklahoma", label: "Oklahoma_label" },
    { value: "Oregon", label: "Oregon_label" },
    { value: "Pennsylvania", label: "Pennsylvania_label" },
    { value: "Rhode Island", label: "Rhode Island_label" },
    { value: "South Carolina", label: "South Carolina_label" },
    { value: "South Dakota", label: "South Dakota_label" },
    { value: "Tennessee", label: "Tennessee_label" },
    { value: "Texas", label: "Texas_label" },
    { value: "Utah", label: "Utah_label" },
    { value: "Vermont", label: "Vermont_label" },
    { value: "Virginia", label: "Virginia_label" },
    { value: "Washington", label: "Washington_label" },
    { value: "West Virginia", label: "West Virginia_label" },
    { value: "Wisconsin", label: "Wisconsin_label" },
    { value: "Wyoming", label: "Wyoming_label" },
    { value: "Puerto Rico", label: "Puerto Rico_label" },
];
